### ISSUE TITLE
training config file

### ISSUE THREAD

**Issue by morgsmss7** [yandex-research/tabular-dl-num-embeddings#12]
Could you provide a sample 0.toml file? I am attempting to run the training scripts on new data and am hitting a few issues I did not hit in tune.py.

**Comment by morgsmss7** [comment]
Hello Yura, 

A default train4.py toml file would be very helpful. Right now, I am using mlp and mlp-plrlr, so an example for those would be quite useful. We are essentially looking to repeat a few of your experiments on our datasets.

Best,
Morgan

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
