### ISSUE TITLE
Parameter values ​​in exp/.../xx.toml

### ISSUE THREAD

**Issue by gy0425** [yandex-research/tabular-dl-num-embeddings#13]
I would like to ask how the values ​​of the parameters in exp/.../xx.toml are obtained? When I reproduce the code, I want to use C.bins.count. The value of the parameter in the toml file is 125, but I don't know how this value is obtained.

**Comment by gy0425** [comment]
For example, the value of the "count" parameter in the exp/transformer-q-l/adult/0_evaluation/0.toml file is 125. How is this value determined?

**Comment by Yura52** [comment]
This section explains how such configs are obtained: [link](https://github.com/yandex-research/tabular-dl-num-embeddings#how-to-reproduce-results).

- Namely, the value `count=125` was tuned _automatically_ based on the hyperparameter tuning
- The hyperparameter tuning is defined by this config: [link](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/exp/transformer-q-l/adult/0_evaluation/0.toml)
- The result of the tuning is here: [link](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/exp/transformer-q-l/adult/0_tuning/report.json)
- the `tuning_report['best']['config']` dictionary is the best configuration identified by the tuning algorithm; in particular, you can see the value `"count": 125` there)

Does this help?

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!

**Comment by gy0425** [comment]
Thanks for your answer, much appreciated.
