### ISSUE TITLE
About periodic config

### ISSUE THREAD

**Issue by Minhvt34** [yandex-research/tabular-dl-num-embeddings#14]
Hi Yura!

I am trying to implement transformer-plr. I cannot find `config.model.periodic` and `config.model.autodis` in report.json file or in default config file. 

I found self.model.periodic = lib.PeriodicOptions(
                self.model.d_num_embedding // 2,
                self.model.periodic_sigma,
                False,
                'log-linear',
            )

But I can not find the implement of autodis.

Thank you!

**Comment by Yura52** [comment]
Hi! See [this line in bin/train4.py](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/bin/train4.py#L181).

To clarify, our paper does not propose AutoDis. AutoDis is a baseline from prior work.

**Comment by Yura52** [comment]
I am not sure that I fully understand the question, do you need help with the "periodic" part?

**Comment by Minhvt34** [comment]
Thank you for your reply!

I found the implement of periodic embedding here [https://github.com/Yura52/rtdl/blob/main/rtdl/nn/_embeddings.py](rtdl-embedding) more practical. Is the implement of numerical embedding in rtdl/nn/embedding.py as same as in the current repo - [tabular-dl-num-embeddings](https://github.com/yandex-research/tabular-dl-num-embeddings)

**Comment by Yura52** [comment]
Well, I hope they are the same :) Though, currently, I recommend copying the implementation from here: [link](https://github.com/yandex-research/tabular-dl-tabr/blob/d628ec7e1c0a66011473021034e7dd4a77740112/lib/deep.py#L175)

Regarding, the rtdl project, please, see [this post](https://github.com/Yura52/rtdl/discussions/53#discussioncomment-6384398) to learn about the status of the project.

**Comment by Minhvt34** [comment]
> Well, I hope they are the same :) Though, currently, I recommend copying the implementation from here: [link](https://github.com/yandex-research/tabular-dl-tabr/blob/d628ec7e1c0a66011473021034e7dd4a77740112/lib/deep.py#L175)
> 
> Regarding, the rtdl project, please, see [this post](https://github.com/Yura52/rtdl/discussions/53#discussioncomment-6384398) to learn about the status of the project.

Thank you!
